spring.application.name=Grocy

spring.datasource.url=jdbc:postgresql://localhost:3300/grocy
spring.datasource.username=grocy_admin
spring.datasource.password=grocy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
